// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://phieoysupudriswzrcrr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBoaWVveXN1cHVkcmlzd3pyY3JyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyOTg4OTEsImV4cCI6MjA3MTg3NDg5MX0.AxgdB4mT4wkdtQP0q_xnB1c5Ql15CxajA1g7IjQ5G2k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});